query Entity($id: ID!) {
  e: productCategory(id: $id) {
    id name description image { __typename id path alt } reviews { id status target { field
    } } version createdAt updatedAt position hidden
  }
}
