query Entity($id: ID!) {
  e: staffMember(id: $id) {
    id name role credentials bio languages photo { __typename id path alt } reviews { id
    status target { field } } version createdAt updatedAt position hidden
  }
}
